AllCops:
  # Best version to pin against as is the most stable generally
  TargetRubyVersion: 2.7

# No difference perf wise on singles or doubles, purely visual
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# Turned off for table driven testing. Generally a good idea to have on
Metrics/BlockLength:
  Enabled: false

# Purely style related, but line lengths in Ruby aren't generally this long
Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
