include:
- "lib/**/*.rb"
- "main.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
- Gemfile.lock
require: []
domains: []
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except:
    - Gemfile.lock
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
